services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD: ""
      REDIS_USER: "user"
      REDIS_USER_PASSWORD: ""
    ports:
      - "6380:6379"
    networks:
      - papersnetwork
    volumes:
      - ./redisdata:/data
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: papersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5434:5432"
    networks:
      - papersnetwork
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./dbInit/dbInit.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  papersnetwork:
    name: papersnetwork
