// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: BalanceService.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceManagement_GetBalance_FullMethodName = "/BalanceService.BalanceManagement/GetBalance"
	BalanceManagement_Add_FullMethodName        = "/BalanceService.BalanceManagement/Add"
	BalanceManagement_Take_FullMethodName       = "/BalanceService.BalanceManagement/Take"
)

// BalanceManagementClient is the client API for BalanceManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceManagementClient interface {
	GetBalance(ctx context.Context, in *User, opts ...grpc.CallOption) (*Balance, error)
	Add(ctx context.Context, in *Money, opts ...grpc.CallOption) (*Balance, error)
	Take(ctx context.Context, in *Money, opts ...grpc.CallOption) (*Balance, error)
}

type balanceManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceManagementClient(cc grpc.ClientConnInterface) BalanceManagementClient {
	return &balanceManagementClient{cc}
}

func (c *balanceManagementClient) GetBalance(ctx context.Context, in *User, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, BalanceManagement_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceManagementClient) Add(ctx context.Context, in *Money, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, BalanceManagement_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceManagementClient) Take(ctx context.Context, in *Money, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, BalanceManagement_Take_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceManagementServer is the server API for BalanceManagement service.
// All implementations must embed UnimplementedBalanceManagementServer
// for forward compatibility.
type BalanceManagementServer interface {
	GetBalance(context.Context, *User) (*Balance, error)
	Add(context.Context, *Money) (*Balance, error)
	Take(context.Context, *Money) (*Balance, error)
	mustEmbedUnimplementedBalanceManagementServer()
}

// UnimplementedBalanceManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceManagementServer struct{}

func (UnimplementedBalanceManagementServer) GetBalance(context.Context, *User) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBalanceManagementServer) Add(context.Context, *Money) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBalanceManagementServer) Take(context.Context, *Money) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Take not implemented")
}
func (UnimplementedBalanceManagementServer) mustEmbedUnimplementedBalanceManagementServer() {}
func (UnimplementedBalanceManagementServer) testEmbeddedByValue()                           {}

// UnsafeBalanceManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceManagementServer will
// result in compilation errors.
type UnsafeBalanceManagementServer interface {
	mustEmbedUnimplementedBalanceManagementServer()
}

func RegisterBalanceManagementServer(s grpc.ServiceRegistrar, srv BalanceManagementServer) {
	// If the following call pancis, it indicates UnimplementedBalanceManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceManagement_ServiceDesc, srv)
}

func _BalanceManagement_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceManagementServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceManagement_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceManagementServer).GetBalance(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceManagement_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Money)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceManagementServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceManagement_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceManagementServer).Add(ctx, req.(*Money))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceManagement_Take_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Money)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceManagementServer).Take(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceManagement_Take_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceManagementServer).Take(ctx, req.(*Money))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceManagement_ServiceDesc is the grpc.ServiceDesc for BalanceManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BalanceService.BalanceManagement",
	HandlerType: (*BalanceManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _BalanceManagement_GetBalance_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _BalanceManagement_Add_Handler,
		},
		{
			MethodName: "Take",
			Handler:    _BalanceManagement_Take_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BalanceService.proto",
}
